name: Check User Assignments on PR Open

on:
  pull_request:
    types: [opened]

jobs:
  check-assignments:
    runs-on: ubuntu-latest
    permissions:
      contents: read
      pull-requests: read
    env:
      BACKEND_URL: https://pullquestgithubbackend-1.onrender.com
    
    steps:
    - name: Get PR assignee or author
      id: get_user
      run: |
        # Check if PR has assignees
        assignees='${{ toJson(github.event.pull_request.assignees) }}'
        pr_author="${{ github.event.pull_request.user.login }}"
        
        if [[ "$assignees" != "[]" ]]; then
          # Extract first assignee username
          username=$(echo "$assignees" | jq -r '.[0].login')
          echo "username=$username" >> $GITHUB_OUTPUT
          echo "✅ Found assignee: $username"
        else
          # Use PR author if no assignee
          echo "username=$pr_author" >> $GITHUB_OUTPUT
          echo "✅ No assignee found, using PR author: $pr_author"
        fi
    
    - name: Debug – print extracted info
      run: |
        echo "🔍 PR Number   : ${{ github.event.pull_request.number }}"
        echo "🔍 Username    : ${{ steps.get_user.outputs.username }}"
        echo "🔍 Repository  : ${{ github.event.repository.full_name }}"
        echo "🔍 Owner       : ${{ github.event.repository.owner.login }}"
        echo "🔍 Repo Name   : ${{ github.event.repository.name }}"
    
    - name: Build payload ➜ POST to backend
      run: |
        PR_NUMBER=${{ github.event.pull_request.number }}
        USERNAME="${{ steps.get_user.outputs.username }}"
        
        # Assemble payload for assignment check
        payload=$(jq -n \
          --arg owner         "${{ github.event.repository.owner.login }}" \
          --arg repo          "${{ github.event.repository.name }}" \
          --arg assignedUser  "$USERNAME" \
          --argjson issueNumber  "$PR_NUMBER" \
          '{
            owner: $owner,
            repo: $repo, 
            issueNumber: $issueNumber,
            assignedUser: $assignedUser
          }')
        
        echo "📦 Payload:"
        echo "$payload"
        
        response=$(curl --fail --show-error --silent \
          -X POST "$BACKEND_URL/api/hactoberfest/IssueAssigned" \
          -H "Content-Type: application/json" \
          --data-raw "$payload" \
          -w '\nHTTP %{http_code}\n' )
        
        echo "🔍 Response: $response"
    
    - name: Done
      run: echo "✅ Assignment check completed and comment posted to PR"